#!/usr/bin/env python3
'''
This program randomly plays the 2048 game at
https://gabrielecirulli.github.io/2048/'
'''
'''
2048 is a simple game where you combine tiles by sliding them up, down,
left, or right with the arrow keys. You can actually get a fairly high
score by repeatedly sliding in an up, right, down, and left pattern
over and over again. Write a program that will open the game at
https://gabrielecirulli.github.io/2048/ and keep sending up, right,
down, and left keystrokes to automatically play the game.
'''

import random
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import sys
import time

keyList = ('Keys.UP', 'Keys.DOWN', 'Keys.LEFT', 'Keys.RIGHT')

# open browser based on the operating system my computer is using
# this became necessary as IDLE on mac OS can not locate the geckodriver
# no such issue when interpreted directly by Python interpreter via
# the command line
if sys.platform == 'win32':
    browser = webdriver.Firefox()
elif sys.platform == 'darwin': # mac OS
    try:
        browser = webdriver.Firefox(\
            executable_path=\
            '/usr/local/Cellar/geckodriver/0.19.0/bin/geckodriver')
    except Exception as excMsg:
        print('problem reaching geckodriver under mac OS: {excMsg}'\
              f'\ntrying another way')
        browser = webdriver.Firefox()
else:
    print('Warning - Unknown OS', sys.platform)
    print('Assuming geckodriver can be accessed properly'\
          'by the Python interpreter.')
    browser = webdriver.Firefox()

browser.get('https://gabrielecirulli.github.io/2048/')
gameElem = browser.find_element_by_class_name('game-container')
gameElem.send_keys(Keys.UP)

for i in range(15):
    key = random.choice(keyList)
    gameElem.send_keys(key)
    time.sleep(1)

print('Moves completed!')
gameElem = browser.find_element_by_class_name('best-container')
print(f'Best score was {gameElem.text}.')

time.sleep(2)
browser.quit()
